use crate::tui::models::Tab;
use crate::tui::state::App;
use crate::tui::ui::helpers::centered_rect;
use ratatui::{
    prelude::*,
    widgets::{Block, Borders, Clear, Paragraph},
};

/// Draw the help overlay
pub fn draw_help_overlay(frame: &mut Frame, area: Rect, app: &App) {
    let help_text = match app.active_tab {
        Tab::Connections => vec![
            "",
            "  Navigation",
            "  ──────────────────────────────────────",
            "  1/2/3       Switch tab",
            "  Tab         Next tab",
            "  ↑/k         Move up",
            "  ↓/j         Move down",
            "  PgUp/PgDn   Page up/down",
            "  g/Home      Go to top",
            "  G/End       Go to bottom",
            "",
            "  Actions",
            "  ──────────────────────────────────────",
            "  Enter       Connect to selected",
            "  a           Add new connection",
            "  s           Show detail pane",
            "  e           Edit connection",
            "  p           Preview SSH command",
            "  d/Delete    Delete connection",
            "  r           Refresh list",
            "  :           Quick connect",
            "",
            "  Selection",
            "  ──────────────────────────────────────",
            "  Space       Toggle select",
            "  Ctrl+A      Select all",
            "  x           Batch delete selected",
            "  Esc         Clear selection",
            "",
            "  Search & Filter",
            "  ──────────────────────────────────────",
            "  /           Start search",
            "  t           Filter by tag",
            "",
            "  View & Sort",
            "  ──────────────────────────────────────",
            "  o           Cycle sort field",
            "  O           Toggle sort direction",
            "  v           Toggle compact view",
            "  f           Toggle group by tag",
            "",
            "  General",
            "  ──────────────────────────────────────",
            "  ?           Toggle this help",
            "  P           Ping selected host",
            "  q/Esc       Quit",
            "",
            "  Indicators: [B] bastion  [K] kerberos",
            "  Ping:  ● reachable  ● unreachable  ◌ checking",
            "",
            "  Esc / q / ? to close",
        ],
        Tab::History => vec![
            "",
            "  Navigation",
            "  ──────────────────────────────────────",
            "  1/2/3       Switch tab",
            "  ↑/k ↓/j     Move up/down",
            "  PgUp/PgDn   Page up/down",
            "",
            "  Actions",
            "  ──────────────────────────────────────",
            "  Enter       Reconnect to session host",
            "  r           Refresh history",
            "  /           Filter by connection name",
            "  f           Toggle show failed only",
            "  o           Cycle sort field",
            "",
            "  General",
            "  ──────────────────────────────────────",
            "  ?           Toggle this help",
            "  q/Esc       Quit",
            "",
            "  Esc / q / ? to close",
        ],
        Tab::Config => vec![
            "",
            "  Navigation",
            "  ──────────────────────────────────────",
            "  1/2/3       Switch tab",
            "  ↑/k ↓/j     Move up/down",
            "",
            "  Actions",
            "  ──────────────────────────────────────",
            "  Enter       Switch to environment",
            "  a           Create new environment",
            "  d/Delete    Delete environment",
            "  r           Refresh list",
            "",
            "  General",
            "  ──────────────────────────────────────",
            "  ?           Toggle this help",
            "  q/Esc       Quit",
            "",
            "  Esc / q / ? to close",
        ],
        Tab::Files => vec![
            "",
            "  Navigation",
            "  ──────────────────────────────────────",
            "  ↑/k ↓/j     Move up/down",
            "  Enter       Enter directory",
            "  ←/h/BS      Go to parent directory",
            "",
            "  Actions",
            "  ──────────────────────────────────────",
            "  d           Download selected file",
            "  u           Upload local file",
            "  D           Delete selected entry",
            "  m           New directory (mkdir)",
            "  R           Rename selected entry",
            "  r           Refresh listing",
            "",
            "  General",
            "  ──────────────────────────────────────",
            "  ?           Toggle this help",
            "  q/Esc       Quit",
            "",
            "  Esc / q / ? to close",
        ],
        Tab::Tunnels => vec![
            "",
            "  Navigation",
            "  ──────────────────────────────────────",
            "  ↑/k ↓/j     Move up/down",
            "  1-5         Switch tab",
            "",
            "  Actions",
            "  ──────────────────────────────────────",
            "  n           New -L port-forward tunnel",
            "  d           New SOCKS5 dynamic proxy (-D)",
            "  x/Delete    Stop selected tunnel",
            "",
            "  Tunnel spec format  (-L)",
            "  ──────────────────────────────────────",
            "  bind_port:remote_host:remote_port",
            "  bind_addr:bind_port:remote_host:remote_port",
            "",
            "  Proxy spec format  (-D)",
            "  ──────────────────────────────────────",
            "  port",
            "  bind_addr:port",
            "",
            "  General",
            "  ──────────────────────────────────────",
            "  ?           Toggle this help",
            "  q/Esc       Quit",
            "",
            "  Esc / q / ? to close",
        ],
    };

    let help_content = help_text.join("\n");

    let popup_width = 54;
    let popup_height = help_text.len() as u16 + 2;
    let popup_area = centered_rect(popup_width, popup_height, area);

    frame.render_widget(Clear, popup_area);

    let help = Paragraph::new(help_content)
        .style(Style::default().fg(Color::White))
        .block(
            Block::default()
                .title(" Help ")
                .title_style(Style::default().fg(Color::Yellow).bold())
                .borders(Borders::ALL)
                .border_style(Style::default().fg(Color::Cyan)),
        );

    frame.render_widget(help, popup_area);
}
