use crate::config::AppConfig;
use crate::models::Connection;
use crate::services::SshService;
use anyhow::{Context, Result};
use std::fs::File;
use std::io::Write;
use tracing::info;

pub enum ExportFormat {
    Json,
    Toml,
    SshConfig,
}

impl std::str::FromStr for ExportFormat {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "json" => Ok(ExportFormat::Json),
            "toml" => Ok(ExportFormat::Toml),
            "ssh-config" | "ssh" => Ok(ExportFormat::SshConfig),
            _ => anyhow::bail!("Invalid export format. Must be 'json', 'toml', or 'ssh-config'"),
        }
    }
}

pub async fn execute(
    format: Option<String>,
    output: Option<String>,
    tag: Option<String>,
    config: AppConfig,
) -> Result<()> {
    let format = format
        .unwrap_or_else(|| "json".to_string())
        .parse::<ExportFormat>()?;

    let ssh_service = SshService::new(config)?;
    let connections = ssh_service.list_connections(tag.as_deref(), false).await?;

    if connections.is_empty() {
        println!("No connections found to export.");
        return Ok(());
    }

    let exported_content = match format {
        ExportFormat::Json => serde_json::to_string_pretty(&connections)?,
        ExportFormat::Toml => toml::to_string_pretty(&ConnectionsWrapper {
            connections: connections.clone(),
        })?,
        ExportFormat::SshConfig => generate_ssh_config(&connections),
    };

    if let Some(output_path) = output {
        let expanded_path = expand_tilde(&output_path);
        let path = std::path::Path::new(&expanded_path);

        if let Some(parent) = path.parent() {
            if !parent.exists() {
                std::fs::create_dir_all(parent).context("Failed to create parent directories")?;
            }
        }

        let mut file = File::create(&expanded_path).context("Failed to create output file")?;
        file.write_all(exported_content.as_bytes())?;
        info!(
            "Exported {} connections to {}",
            connections.len(),
            expanded_path
        );
        println!(
            "✅ Exported {} connections to {}",
            connections.len(),
            expanded_path
        );
    } else {
        println!("{}", exported_content);
    }

    Ok(())
}

#[derive(serde::Serialize)]
struct ConnectionsWrapper {
    connections: Vec<Connection>,
}

fn generate_ssh_config(connections: &[Connection]) -> String {
    let mut config = String::new();
    config.push_str("# Generated by Bayesian SSH\n\n");

    for conn in connections {
        config.push_str(&format!("Host {}\n", conn.name));
        config.push_str(&format!("    HostName {}\n", conn.host));
        config.push_str(&format!("    User {}\n", conn.user));
        config.push_str(&format!("    Port {}\n", conn.port));

        if let Some(key) = &conn.key_path {
            config.push_str(&format!("    IdentityFile {}\n", key));
        }

        if let Some(bastion) = &conn.bastion {
            let bastion_user = conn.bastion_user.as_deref().unwrap_or(&conn.user);
            config.push_str(&format!(
                "    ProxyCommand ssh -W %h:%p {}@{}\n",
                bastion_user, bastion
            ));
        }

        if conn.use_kerberos {
            config.push_str("    GSSAPIAuthentication yes\n");
            config.push_str("    GSSAPIDelegateCredentials yes\n");
        }

        config.push('\n');
    }

    config
}

fn expand_tilde(path: &str) -> String {
    if let Some(stripped) = path.strip_prefix("~/") {
        if let Some(mut home) = dirs::home_dir() {
            home.push(stripped);
            return home.to_string_lossy().into_owned();
        }
    }
    path.to_string()
}
